bedtools coverage -d -abam sam_ion/S01_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S01.tsv
bedtools coverage -d -abam sam_ion/S02_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S02.tsv
bedtools coverage -d -abam sam_ion/S03_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S03.tsv
bedtools coverage -d -abam sam_ion/S04_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S04.tsv
bedtools coverage -d -abam sam_ion/S05_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S05.tsv
bedtools coverage -d -abam sam_ion/S06_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S06.tsv
bedtools coverage -d -abam sam_ion/S07_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S07.tsv
bedtools coverage -d -abam sam_ion/S08_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S08.tsv
bedtools coverage -d -abam sam_ion/S09_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S09.tsv
bedtools coverage -d -abam sam_ion/S10_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S10.tsv
bedtools coverage -d -abam sam_ion/S11_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S11.tsv
bedtools coverage -d -abam sam_ion/S12_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S12.tsv
bedtools coverage -d -abam sam_ion/S13_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S13.tsv
bedtools coverage -d -abam sam_ion/S14_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S14.tsv
bedtools coverage -d -abam sam_ion/S15_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S15.tsv
bedtools coverage -d -abam sam_ion/S16_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S16.tsv
bedtools coverage -d -abam sam_ion/S17_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S17.tsv
bedtools coverage -d -abam sam_ion/S18_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S18.tsv
bedtools coverage -d -abam sam_ion/S19_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S19.tsv
bedtools coverage -d -abam sam_ion/S20_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S20.tsv
bedtools coverage -d -abam sam_ion/S21_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S21.tsv
bedtools coverage -d -abam sam_ion/S22_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S22.tsv
bedtools coverage -d -abam sam_ion/S23_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S23.tsv
bedtools coverage -d -abam sam_ion/S24_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S24.tsv
bedtools coverage -d -abam sam_ion/S25_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S25.tsv
bedtools coverage -d -abam sam_ion/S26_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S26.tsv
bedtools coverage -d -abam sam_ion/S27_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S27.tsv
bedtools coverage -d -abam sam_ion/S28_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S28.tsv
bedtools coverage -d -abam sam_ion/S29_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S29.tsv
bedtools coverage -d -abam sam_ion/S30_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S30.tsv
bedtools coverage -d -abam sam_ion/S31_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S31.tsv
bedtools coverage -d -abam sam_ion/S32_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S32.tsv
bedtools coverage -d -abam sam_ion/S33_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S33.tsv
bedtools coverage -d -abam sam_ion/S34_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S34.tsv
bedtools coverage -d -abam sam_ion/S35_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S35.tsv
bedtools coverage -d -abam sam_ion/S36_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S36.tsv
bedtools coverage -d -abam sam_ion/S37_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S37.tsv
bedtools coverage -d -abam sam_ion/S38_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S38.tsv
bedtools coverage -d -abam sam_ion/S39_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S39.tsv
bedtools coverage -d -abam sam_ion/S40_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S40.tsv
bedtools coverage -d -abam sam_ion/S41_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S41.tsv
bedtools coverage -d -abam sam_ion/S42_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S42.tsv
bedtools coverage -d -abam sam_ion/S43_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S43.tsv
bedtools coverage -d -abam sam_ion/S44_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S44.tsv
bedtools coverage -d -abam sam_ion/S45_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S45.tsv
bedtools coverage -d -abam sam_ion/S46_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S46.tsv
bedtools coverage -d -abam sam_ion/S47_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_ion/S47.tsv
bedtools coverage -d -abam sam_miseq/S00_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S00.tsv
bedtools coverage -d -abam sam_miseq/S01_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S01.tsv
bedtools coverage -d -abam sam_miseq/S02_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S02.tsv
bedtools coverage -d -abam sam_miseq/S03_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S03.tsv
bedtools coverage -d -abam sam_miseq/S04_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S04.tsv
bedtools coverage -d -abam sam_miseq/S05_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S05.tsv
bedtools coverage -d -abam sam_miseq/S06_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S06.tsv
bedtools coverage -d -abam sam_miseq/S07_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S07.tsv
bedtools coverage -d -abam sam_miseq/S08_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S08.tsv
bedtools coverage -d -abam sam_miseq/S09_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S09.tsv
bedtools coverage -d -abam sam_miseq/S10_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S10.tsv
bedtools coverage -d -abam sam_miseq/S11_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S11.tsv
bedtools coverage -d -abam sam_miseq/S12_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S12.tsv
bedtools coverage -d -abam sam_miseq/S13_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S13.tsv
bedtools coverage -d -abam sam_miseq/S14_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S14.tsv
bedtools coverage -d -abam sam_miseq/S15_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S15.tsv
bedtools coverage -d -abam sam_miseq/S16_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S16.tsv
bedtools coverage -d -abam sam_miseq/S17_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S17.tsv
bedtools coverage -d -abam sam_miseq/S18_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S18.tsv
bedtools coverage -d -abam sam_miseq/S19_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S19.tsv
bedtools coverage -d -abam sam_miseq/S20_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S20.tsv
bedtools coverage -d -abam sam_miseq/S21_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S21.tsv
bedtools coverage -d -abam sam_miseq/S22_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S22.tsv
bedtools coverage -d -abam sam_miseq/S23_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S23.tsv
bedtools coverage -d -abam sam_miseq/S24_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S24.tsv
bedtools coverage -d -abam sam_miseq/S25_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S25.tsv
bedtools coverage -d -abam sam_miseq/S26_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S26.tsv
bedtools coverage -d -abam sam_miseq/S27_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S27.tsv
bedtools coverage -d -abam sam_miseq/S28_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S28.tsv
bedtools coverage -d -abam sam_miseq/S29_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S29.tsv
bedtools coverage -d -abam sam_miseq/S30_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S30.tsv
bedtools coverage -d -abam sam_miseq/S31_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S31.tsv
bedtools coverage -d -abam sam_miseq/S32_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S32.tsv
bedtools coverage -d -abam sam_miseq/S33_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S33.tsv
bedtools coverage -d -abam sam_miseq/S34_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S34.tsv
bedtools coverage -d -abam sam_miseq/S35_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S35.tsv
bedtools coverage -d -abam sam_miseq/S36_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S36.tsv
bedtools coverage -d -abam sam_miseq/S37_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S37.tsv
bedtools coverage -d -abam sam_miseq/S38_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S38.tsv
bedtools coverage -d -abam sam_miseq/S39_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S39.tsv
bedtools coverage -d -abam sam_miseq/S40_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S40.tsv
bedtools coverage -d -abam sam_miseq/S41_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S41.tsv
bedtools coverage -d -abam sam_miseq/S42_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S42.tsv
bedtools coverage -d -abam sam_miseq/S43_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S43.tsv
bedtools coverage -d -abam sam_miseq/S44_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S44.tsv
bedtools coverage -d -abam sam_miseq/S45_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S45.tsv
bedtools coverage -d -abam sam_miseq/S46_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S46.tsv
bedtools coverage -d -abam sam_miseq/S47_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S47.tsv
bedtools coverage -d -abam sam_miseq/S48_dedup.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_miseq/S48.tsv


bedtools coverage -d -abam sam_basespace/10_S10.bam  -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/10.tsv
bedtools coverage -d -abam sam_basespace/11_S11.bam  -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/11.tsv
bedtools coverage -d -abam sam_basespace/12_S12.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/12.tsv
bedtools coverage -d -abam sam_basespace/13_S13.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/13.tsv
bedtools coverage -d -abam sam_basespace/14_S14.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/14.tsv
bedtools coverage -d -abam sam_basespace/15_S15.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/15.tsv
bedtools coverage -d -abam sam_basespace/16_S16.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/16.tsv
bedtools coverage -d -abam sam_basespace/17_S17.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/17.tsv
bedtools coverage -d -abam sam_basespace/18_S18.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/18.tsv
bedtools coverage -d -abam sam_basespace/19_S19.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/19.tsv
bedtools coverage -d -abam sam_basespace/1_S1.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/1.tsv
bedtools coverage -d -abam sam_basespace/20_S20.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/20.tsv
bedtools coverage -d -abam sam_basespace/21_S21.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/21.tsv
bedtools coverage -d -abam sam_basespace/22_S22.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/22.tsv
bedtools coverage -d -abam sam_basespace/23_S23.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/23.tsv
bedtools coverage -d -abam sam_basespace/24_S24.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/24.tsv
bedtools coverage -d -abam sam_basespace/25_S25.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/25.tsv
bedtools coverage -d -abam sam_basespace/26_S26.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/26.tsv
bedtools coverage -d -abam sam_basespace/27_S27.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/27.tsv
bedtools coverage -d -abam sam_basespace/28_S28.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/28.tsv
bedtools coverage -d -abam sam_basespace/29_S29.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/29.tsv
bedtools coverage -d -abam sam_basespace/2_S2.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/2.tsv
bedtools coverage -d -abam sam_basespace/30_S30.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/30.tsv
bedtools coverage -d -abam sam_basespace/31_S31.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/31.tsv
bedtools coverage -d -abam sam_basespace/32_S32.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/32.tsv
bedtools coverage -d -abam sam_basespace/33_S33.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/33.tsv
bedtools coverage -d -abam sam_basespace/34_S34.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/34.tsv
bedtools coverage -d -abam sam_basespace/35_S35.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/35.tsv
bedtools coverage -d -abam sam_basespace/36_S36.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/36.tsv
bedtools coverage -d -abam sam_basespace/37_S37.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/37.tsv
bedtools coverage -d -abam sam_basespace/38_S38.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/38.tsv
bedtools coverage -d -abam sam_basespace/39_S39.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/39.tsv
bedtools coverage -d -abam sam_basespace/3_S3.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/3.tsv
bedtools coverage -d -abam sam_basespace/40_S40.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/40.tsv
bedtools coverage -d -abam sam_basespace/41_S41.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/41.tsv
bedtools coverage -d -abam sam_basespace/42_S42.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/42.tsv
bedtools coverage -d -abam sam_basespace/43_S43.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/43.tsv
bedtools coverage -d -abam sam_basespace/44_S44.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/44.tsv
bedtools coverage -d -abam sam_basespace/45_S45.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/45.tsv
bedtools coverage -d -abam sam_basespace/46_S46.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/46.tsv
bedtools coverage -d -abam sam_basespace/47_S47.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/47.tsv
bedtools coverage -d -abam sam_basespace/48_S48.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/48.tsv
bedtools coverage -d -abam sam_basespace/4_S4.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/4.tsv
bedtools coverage -d -abam sam_basespace/5_S5.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/5.tsv
bedtools coverage -d -abam sam_basespace/6_S6.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/6.tsv
bedtools coverage -d -abam sam_basespace/7_S7.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/7.tsv
bedtools coverage -d -abam sam_basespace/8_S8.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/8.tsv
bedtools coverage -d -abam sam_basespace/9_S9.bam -b targets/solo_genes.bed | awk '{print $4,$6}' > depth_basespace/9.tsv
