vcf-isec -n +2 vcf_ion/S01_sorted.vcf.gz vcf_miseq/S01_sorted.vcf.gz > vcf_miseq_ion_isecd/S01_isecd.vcf
vcf-isec -n +2 vcf_ion/S02_sorted.vcf.gz vcf_miseq/S02_sorted.vcf.gz > vcf_miseq_ion_isecd/S02_isecd.vcf
vcf-isec -n +2 vcf_ion/S03_sorted.vcf.gz vcf_miseq/S03_sorted.vcf.gz > vcf_miseq_ion_isecd/S03_isecd.vcf
vcf-isec -n +2 vcf_ion/S04_sorted.vcf.gz vcf_miseq/S04_sorted.vcf.gz > vcf_miseq_ion_isecd/S04_isecd.vcf
vcf-isec -n +2 vcf_ion/S05_sorted.vcf.gz vcf_miseq/S05_sorted.vcf.gz > vcf_miseq_ion_isecd/S05_isecd.vcf
vcf-isec -n +2 vcf_ion/S06_sorted.vcf.gz vcf_miseq/S06_sorted.vcf.gz > vcf_miseq_ion_isecd/S06_isecd.vcf
vcf-isec -n +2 vcf_ion/S07_sorted.vcf.gz vcf_miseq/S07_sorted.vcf.gz > vcf_miseq_ion_isecd/S07_isecd.vcf
vcf-isec -n +2 vcf_ion/S08_sorted.vcf.gz vcf_miseq/S08_sorted.vcf.gz > vcf_miseq_ion_isecd/S08_isecd.vcf
vcf-isec -n +2 vcf_ion/S09_sorted.vcf.gz vcf_miseq/S09_sorted.vcf.gz > vcf_miseq_ion_isecd/S09_isecd.vcf
vcf-isec -n +2 vcf_ion/S10_sorted.vcf.gz vcf_miseq/S10_sorted.vcf.gz > vcf_miseq_ion_isecd/S10_isecd.vcf
vcf-isec -n +2 vcf_ion/S11_sorted.vcf.gz vcf_miseq/S11_sorted.vcf.gz > vcf_miseq_ion_isecd/S11_isecd.vcf
vcf-isec -n +2 vcf_ion/S12_sorted.vcf.gz vcf_miseq/S12_sorted.vcf.gz > vcf_miseq_ion_isecd/S12_isecd.vcf
vcf-isec -n +2 vcf_ion/S13_sorted.vcf.gz vcf_miseq/S13_sorted.vcf.gz > vcf_miseq_ion_isecd/S13_isecd.vcf
vcf-isec -n +2 vcf_ion/S14_sorted.vcf.gz vcf_miseq/S14_sorted.vcf.gz > vcf_miseq_ion_isecd/S14_isecd.vcf
vcf-isec -n +2 vcf_ion/S15_sorted.vcf.gz vcf_miseq/S15_sorted.vcf.gz > vcf_miseq_ion_isecd/S15_isecd.vcf
vcf-isec -n +2 vcf_ion/S16_sorted.vcf.gz vcf_miseq/S16_sorted.vcf.gz > vcf_miseq_ion_isecd/S16_isecd.vcf
vcf-isec -n +2 vcf_ion/S17_sorted.vcf.gz vcf_miseq/S17_sorted.vcf.gz > vcf_miseq_ion_isecd/S17_isecd.vcf
vcf-isec -n +2 vcf_ion/S18_sorted.vcf.gz vcf_miseq/S18_sorted.vcf.gz > vcf_miseq_ion_isecd/S18_isecd.vcf
vcf-isec -n +2 vcf_ion/S19_sorted.vcf.gz vcf_miseq/S19_sorted.vcf.gz > vcf_miseq_ion_isecd/S19_isecd.vcf
vcf-isec -n +2 vcf_ion/S20_sorted.vcf.gz vcf_miseq/S20_sorted.vcf.gz > vcf_miseq_ion_isecd/S20_isecd.vcf
vcf-isec -n +2 vcf_ion/S21_sorted.vcf.gz vcf_miseq/S21_sorted.vcf.gz > vcf_miseq_ion_isecd/S21_isecd.vcf
vcf-isec -n +2 vcf_ion/S22_sorted.vcf.gz vcf_miseq/S22_sorted.vcf.gz > vcf_miseq_ion_isecd/S22_isecd.vcf
vcf-isec -n +2 vcf_ion/S23_sorted.vcf.gz vcf_miseq/S23_sorted.vcf.gz > vcf_miseq_ion_isecd/S23_isecd.vcf
vcf-isec -n +2 vcf_ion/S24_sorted.vcf.gz vcf_miseq/S24_sorted.vcf.gz > vcf_miseq_ion_isecd/S24_isecd.vcf
vcf-isec -n +2 vcf_ion/S25_sorted.vcf.gz vcf_miseq/S25_sorted.vcf.gz > vcf_miseq_ion_isecd/S25_isecd.vcf
vcf-isec -n +2 vcf_ion/S26_sorted.vcf.gz vcf_miseq/S26_sorted.vcf.gz > vcf_miseq_ion_isecd/S26_isecd.vcf
vcf-isec -n +2 vcf_ion/S27_sorted.vcf.gz vcf_miseq/S27_sorted.vcf.gz > vcf_miseq_ion_isecd/S27_isecd.vcf
vcf-isec -n +2 vcf_ion/S28_sorted.vcf.gz vcf_miseq/S28_sorted.vcf.gz > vcf_miseq_ion_isecd/S28_isecd.vcf
vcf-isec -n +2 vcf_ion/S29_sorted.vcf.gz vcf_miseq/S29_sorted.vcf.gz > vcf_miseq_ion_isecd/S29_isecd.vcf
vcf-isec -n +2 vcf_ion/S30_sorted.vcf.gz vcf_miseq/S30_sorted.vcf.gz > vcf_miseq_ion_isecd/S30_isecd.vcf
vcf-isec -n +2 vcf_ion/S31_sorted.vcf.gz vcf_miseq/S31_sorted.vcf.gz > vcf_miseq_ion_isecd/S31_isecd.vcf
vcf-isec -n +2 vcf_ion/S32_sorted.vcf.gz vcf_miseq/S32_sorted.vcf.gz > vcf_miseq_ion_isecd/S32_isecd.vcf
vcf-isec -n +2 vcf_ion/S33_sorted.vcf.gz vcf_miseq/S33_sorted.vcf.gz > vcf_miseq_ion_isecd/S33_isecd.vcf
vcf-isec -n +2 vcf_ion/S34_sorted.vcf.gz vcf_miseq/S34_sorted.vcf.gz > vcf_miseq_ion_isecd/S34_isecd.vcf
vcf-isec -n +2 vcf_ion/S35_sorted.vcf.gz vcf_miseq/S35_sorted.vcf.gz > vcf_miseq_ion_isecd/S35_isecd.vcf
vcf-isec -n +2 vcf_ion/S36_sorted.vcf.gz vcf_miseq/S36_sorted.vcf.gz > vcf_miseq_ion_isecd/S36_isecd.vcf
vcf-isec -n +2 vcf_ion/S37_sorted.vcf.gz vcf_miseq/S37_sorted.vcf.gz > vcf_miseq_ion_isecd/S37_isecd.vcf
vcf-isec -n +2 vcf_ion/S38_sorted.vcf.gz vcf_miseq/S38_sorted.vcf.gz > vcf_miseq_ion_isecd/S38_isecd.vcf
vcf-isec -n +2 vcf_ion/S39_sorted.vcf.gz vcf_miseq/S39_sorted.vcf.gz > vcf_miseq_ion_isecd/S39_isecd.vcf
vcf-isec -n +2 vcf_ion/S40_sorted.vcf.gz vcf_miseq/S40_sorted.vcf.gz > vcf_miseq_ion_isecd/S40_isecd.vcf
vcf-isec -n +2 vcf_ion/S41_sorted.vcf.gz vcf_miseq/S41_sorted.vcf.gz > vcf_miseq_ion_isecd/S41_isecd.vcf
vcf-isec -n +2 vcf_ion/S42_sorted.vcf.gz vcf_miseq/S42_sorted.vcf.gz > vcf_miseq_ion_isecd/S42_isecd.vcf
vcf-isec -n +2 vcf_ion/S43_sorted.vcf.gz vcf_miseq/S43_sorted.vcf.gz > vcf_miseq_ion_isecd/S43_isecd.vcf
vcf-isec -n +2 vcf_ion/S44_sorted.vcf.gz vcf_miseq/S44_sorted.vcf.gz > vcf_miseq_ion_isecd/S44_isecd.vcf
vcf-isec -n +2 vcf_ion/S45_sorted.vcf.gz vcf_miseq/S45_sorted.vcf.gz > vcf_miseq_ion_isecd/S45_isecd.vcf
vcf-isec -n +2 vcf_ion/S46_sorted.vcf.gz vcf_miseq/S46_sorted.vcf.gz > vcf_miseq_ion_isecd/S46_isecd.vcf
vcf-isec -n +2 vcf_ion/S47_sorted.vcf.gz vcf_miseq/S47_sorted.vcf.gz > vcf_miseq_ion_isecd/S47_isecd.vcf
