vcf-merge vcf_ion/S01_sorted.vcf.gz vcf_miseq/S01_sorted.vcf.gz > vcf_miseq_ion_merged/S01_merged.vcf
vcf-merge vcf_ion/S02_sorted.vcf.gz vcf_miseq/S02_sorted.vcf.gz > vcf_miseq_ion_merged/S02_merged.vcf
vcf-merge vcf_ion/S03_sorted.vcf.gz vcf_miseq/S03_sorted.vcf.gz > vcf_miseq_ion_merged/S03_merged.vcf
vcf-merge vcf_ion/S04_sorted.vcf.gz vcf_miseq/S04_sorted.vcf.gz > vcf_miseq_ion_merged/S04_merged.vcf
vcf-merge vcf_ion/S05_sorted.vcf.gz vcf_miseq/S05_sorted.vcf.gz > vcf_miseq_ion_merged/S05_merged.vcf
vcf-merge vcf_ion/S06_sorted.vcf.gz vcf_miseq/S06_sorted.vcf.gz > vcf_miseq_ion_merged/S06_merged.vcf
vcf-merge vcf_ion/S07_sorted.vcf.gz vcf_miseq/S07_sorted.vcf.gz > vcf_miseq_ion_merged/S07_merged.vcf
vcf-merge vcf_ion/S08_sorted.vcf.gz vcf_miseq/S08_sorted.vcf.gz > vcf_miseq_ion_merged/S08_merged.vcf
vcf-merge vcf_ion/S09_sorted.vcf.gz vcf_miseq/S09_sorted.vcf.gz > vcf_miseq_ion_merged/S09_merged.vcf
vcf-merge vcf_ion/S10_sorted.vcf.gz vcf_miseq/S10_sorted.vcf.gz > vcf_miseq_ion_merged/S10_merged.vcf
vcf-merge vcf_ion/S11_sorted.vcf.gz vcf_miseq/S11_sorted.vcf.gz > vcf_miseq_ion_merged/S11_merged.vcf
vcf-merge vcf_ion/S12_sorted.vcf.gz vcf_miseq/S12_sorted.vcf.gz > vcf_miseq_ion_merged/S12_merged.vcf
vcf-merge vcf_ion/S13_sorted.vcf.gz vcf_miseq/S13_sorted.vcf.gz > vcf_miseq_ion_merged/S13_merged.vcf
vcf-merge vcf_ion/S14_sorted.vcf.gz vcf_miseq/S14_sorted.vcf.gz > vcf_miseq_ion_merged/S14_merged.vcf
vcf-merge vcf_ion/S15_sorted.vcf.gz vcf_miseq/S15_sorted.vcf.gz > vcf_miseq_ion_merged/S15_merged.vcf
vcf-merge vcf_ion/S16_sorted.vcf.gz vcf_miseq/S16_sorted.vcf.gz > vcf_miseq_ion_merged/S16_merged.vcf
vcf-merge vcf_ion/S17_sorted.vcf.gz vcf_miseq/S17_sorted.vcf.gz > vcf_miseq_ion_merged/S17_merged.vcf
vcf-merge vcf_ion/S18_sorted.vcf.gz vcf_miseq/S18_sorted.vcf.gz > vcf_miseq_ion_merged/S18_merged.vcf
vcf-merge vcf_ion/S19_sorted.vcf.gz vcf_miseq/S19_sorted.vcf.gz > vcf_miseq_ion_merged/S19_merged.vcf
vcf-merge vcf_ion/S20_sorted.vcf.gz vcf_miseq/S20_sorted.vcf.gz > vcf_miseq_ion_merged/S20_merged.vcf
vcf-merge vcf_ion/S21_sorted.vcf.gz vcf_miseq/S21_sorted.vcf.gz > vcf_miseq_ion_merged/S21_merged.vcf
vcf-merge vcf_ion/S22_sorted.vcf.gz vcf_miseq/S22_sorted.vcf.gz > vcf_miseq_ion_merged/S22_merged.vcf
vcf-merge vcf_ion/S23_sorted.vcf.gz vcf_miseq/S23_sorted.vcf.gz > vcf_miseq_ion_merged/S23_merged.vcf
vcf-merge vcf_ion/S24_sorted.vcf.gz vcf_miseq/S24_sorted.vcf.gz > vcf_miseq_ion_merged/S24_merged.vcf
vcf-merge vcf_ion/S25_sorted.vcf.gz vcf_miseq/S25_sorted.vcf.gz > vcf_miseq_ion_merged/S25_merged.vcf
vcf-merge vcf_ion/S26_sorted.vcf.gz vcf_miseq/S26_sorted.vcf.gz > vcf_miseq_ion_merged/S26_merged.vcf
vcf-merge vcf_ion/S27_sorted.vcf.gz vcf_miseq/S27_sorted.vcf.gz > vcf_miseq_ion_merged/S27_merged.vcf
vcf-merge vcf_ion/S28_sorted.vcf.gz vcf_miseq/S28_sorted.vcf.gz > vcf_miseq_ion_merged/S28_merged.vcf
vcf-merge vcf_ion/S29_sorted.vcf.gz vcf_miseq/S29_sorted.vcf.gz > vcf_miseq_ion_merged/S29_merged.vcf
vcf-merge vcf_ion/S30_sorted.vcf.gz vcf_miseq/S30_sorted.vcf.gz > vcf_miseq_ion_merged/S30_merged.vcf
vcf-merge vcf_ion/S31_sorted.vcf.gz vcf_miseq/S31_sorted.vcf.gz > vcf_miseq_ion_merged/S31_merged.vcf
vcf-merge vcf_ion/S32_sorted.vcf.gz vcf_miseq/S32_sorted.vcf.gz > vcf_miseq_ion_merged/S32_merged.vcf
vcf-merge vcf_ion/S33_sorted.vcf.gz vcf_miseq/S33_sorted.vcf.gz > vcf_miseq_ion_merged/S33_merged.vcf
vcf-merge vcf_ion/S34_sorted.vcf.gz vcf_miseq/S34_sorted.vcf.gz > vcf_miseq_ion_merged/S34_merged.vcf
vcf-merge vcf_ion/S35_sorted.vcf.gz vcf_miseq/S35_sorted.vcf.gz > vcf_miseq_ion_merged/S35_merged.vcf
vcf-merge vcf_ion/S36_sorted.vcf.gz vcf_miseq/S36_sorted.vcf.gz > vcf_miseq_ion_merged/S36_merged.vcf
vcf-merge vcf_ion/S37_sorted.vcf.gz vcf_miseq/S37_sorted.vcf.gz > vcf_miseq_ion_merged/S37_merged.vcf
vcf-merge vcf_ion/S38_sorted.vcf.gz vcf_miseq/S38_sorted.vcf.gz > vcf_miseq_ion_merged/S38_merged.vcf
vcf-merge vcf_ion/S39_sorted.vcf.gz vcf_miseq/S39_sorted.vcf.gz > vcf_miseq_ion_merged/S39_merged.vcf
vcf-merge vcf_ion/S40_sorted.vcf.gz vcf_miseq/S40_sorted.vcf.gz > vcf_miseq_ion_merged/S40_merged.vcf
vcf-merge vcf_ion/S41_sorted.vcf.gz vcf_miseq/S41_sorted.vcf.gz > vcf_miseq_ion_merged/S41_merged.vcf
vcf-merge vcf_ion/S42_sorted.vcf.gz vcf_miseq/S42_sorted.vcf.gz > vcf_miseq_ion_merged/S42_merged.vcf
vcf-merge vcf_ion/S43_sorted.vcf.gz vcf_miseq/S43_sorted.vcf.gz > vcf_miseq_ion_merged/S43_merged.vcf
vcf-merge vcf_ion/S44_sorted.vcf.gz vcf_miseq/S44_sorted.vcf.gz > vcf_miseq_ion_merged/S44_merged.vcf
vcf-merge vcf_ion/S45_sorted.vcf.gz vcf_miseq/S45_sorted.vcf.gz > vcf_miseq_ion_merged/S45_merged.vcf
vcf-merge vcf_ion/S46_sorted.vcf.gz vcf_miseq/S46_sorted.vcf.gz > vcf_miseq_ion_merged/S46_merged.vcf
vcf-merge vcf_ion/S47_sorted.vcf.gz vcf_miseq/S47_sorted.vcf.gz > vcf_miseq_ion_merged/S47_merged.vcf
