python vcf2provean.py --vcfin vcf_basespace/S01.vcf --out vcf_basespace/S01_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S02.vcf --out vcf_basespace/S02_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S03.vcf --out vcf_basespace/S03_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S04.vcf --out vcf_basespace/S04_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S05.vcf --out vcf_basespace/S05_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S06.vcf --out vcf_basespace/S06_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S07.vcf --out vcf_basespace/S07_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S08.vcf --out vcf_basespace/S08_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S09.vcf --out vcf_basespace/S09_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S10.vcf --out vcf_basespace/S10_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S11.vcf --out vcf_basespace/S11_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S12.vcf --out vcf_basespace/S12_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S13.vcf --out vcf_basespace/S13_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S14.vcf --out vcf_basespace/S14_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S15.vcf --out vcf_basespace/S15_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S16.vcf --out vcf_basespace/S16_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S17.vcf --out vcf_basespace/S17_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S18.vcf --out vcf_basespace/S18_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S19.vcf --out vcf_basespace/S19_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S20.vcf --out vcf_basespace/S20_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S21.vcf --out vcf_basespace/S21_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S22.vcf --out vcf_basespace/S22_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S23.vcf --out vcf_basespace/S23_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S24.vcf --out vcf_basespace/S24_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S25.vcf --out vcf_basespace/S25_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S26.vcf --out vcf_basespace/S26_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S27.vcf --out vcf_basespace/S27_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S28.vcf --out vcf_basespace/S28_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S29.vcf --out vcf_basespace/S29_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S30.vcf --out vcf_basespace/S30_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S31.vcf --out vcf_basespace/S31_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S32.vcf --out vcf_basespace/S32_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S33.vcf --out vcf_basespace/S33_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S34.vcf --out vcf_basespace/S34_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S35.vcf --out vcf_basespace/S35_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S36.vcf --out vcf_basespace/S36_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S37.vcf --out vcf_basespace/S37_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S38.vcf --out vcf_basespace/S38_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S39.vcf --out vcf_basespace/S39_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S40.vcf --out vcf_basespace/S40_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S41.vcf --out vcf_basespace/S41_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S42.vcf --out vcf_basespace/S42_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S43.vcf --out vcf_basespace/S43_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S44.vcf --out vcf_basespace/S44_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S45.vcf --out vcf_basespace/S45_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S46.vcf --out vcf_basespace/S46_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S47.vcf --out vcf_basespace/S47_provean.csv
python vcf2provean.py --vcfin vcf_basespace/S48.vcf --out vcf_basespace/S48_provean.csv
