python vcf_sort.py --vcfin vcf_basespace/S01.vcf > vcf_basespace/S01_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S02.vcf > vcf_basespace/S02_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S03.vcf > vcf_basespace/S03_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S04.vcf > vcf_basespace/S04_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S05.vcf > vcf_basespace/S05_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S06.vcf > vcf_basespace/S06_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S07.vcf > vcf_basespace/S07_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S08.vcf > vcf_basespace/S08_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S09.vcf > vcf_basespace/S09_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S10.vcf > vcf_basespace/S10_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S11.vcf > vcf_basespace/S11_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S12.vcf > vcf_basespace/S12_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S13.vcf > vcf_basespace/S13_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S14.vcf > vcf_basespace/S14_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S15.vcf > vcf_basespace/S15_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S16.vcf > vcf_basespace/S16_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S17.vcf > vcf_basespace/S17_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S18.vcf > vcf_basespace/S18_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S19.vcf > vcf_basespace/S19_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S20.vcf > vcf_basespace/S20_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S21.vcf > vcf_basespace/S21_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S22.vcf > vcf_basespace/S22_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S23.vcf > vcf_basespace/S23_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S24.vcf > vcf_basespace/S24_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S25.vcf > vcf_basespace/S25_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S26.vcf > vcf_basespace/S26_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S27.vcf > vcf_basespace/S27_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S28.vcf > vcf_basespace/S28_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S29.vcf > vcf_basespace/S29_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S30.vcf > vcf_basespace/S30_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S31.vcf > vcf_basespace/S31_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S32.vcf > vcf_basespace/S32_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S33.vcf > vcf_basespace/S33_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S34.vcf > vcf_basespace/S34_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S35.vcf > vcf_basespace/S35_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S36.vcf > vcf_basespace/S36_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S37.vcf > vcf_basespace/S37_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S38.vcf > vcf_basespace/S38_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S39.vcf > vcf_basespace/S39_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S40.vcf > vcf_basespace/S40_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S41.vcf > vcf_basespace/S41_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S42.vcf > vcf_basespace/S42_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S43.vcf > vcf_basespace/S43_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S44.vcf > vcf_basespace/S44_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S45.vcf > vcf_basespace/S45_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S46.vcf > vcf_basespace/S46_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S47.vcf > vcf_basespace/S47_sorted.vcf
python vcf_sort.py --vcfin vcf_basespace/S48.vcf > vcf_basespace/S48_sorted.vcf
