VEP=/export/home/rgarcia/software/ensembl-tools-release-79/scripts/variant_effect_predictor/variant_effect_predictor.pl



$VEP -i vcf/intersections/S01.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S01.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S01.mistery.intersected.vcf --json -o vcf/intersections/S01.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S02.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S02.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S02.mistery.intersected.vcf --json -o vcf/intersections/S02.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S03.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S03.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S03.mistery.intersected.vcf --json -o vcf/intersections/S03.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S04.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S04.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S04.mistery.intersected.vcf --json -o vcf/intersections/S04.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S05.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S05.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S05.mistery.intersected.vcf --json -o vcf/intersections/S05.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S06.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S06.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S06.mistery.intersected.vcf --json -o vcf/intersections/S06.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S07.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S07.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S07.mistery.intersected.vcf --json -o vcf/intersections/S07.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S08.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S08.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S08.mistery.intersected.vcf --json -o vcf/intersections/S08.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S09.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S09.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S09.mistery.intersected.vcf --json -o vcf/intersections/S09.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S10.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S10.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S10.mistery.intersected.vcf --json -o vcf/intersections/S10.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S11.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S11.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S11.mistery.intersected.vcf --json -o vcf/intersections/S11.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S12.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S12.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S12.mistery.intersected.vcf --json -o vcf/intersections/S12.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S13.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S13.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S13.mistery.intersected.vcf --json -o vcf/intersections/S13.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S14.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S14.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S14.mistery.intersected.vcf --json -o vcf/intersections/S14.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S15.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S15.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S15.mistery.intersected.vcf --json -o vcf/intersections/S15.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S16.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S16.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S16.mistery.intersected.vcf --json -o vcf/intersections/S16.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S17.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S17.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S17.mistery.intersected.vcf --json -o vcf/intersections/S17.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S18.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S18.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S18.mistery.intersected.vcf --json -o vcf/intersections/S18.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S19.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S19.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S19.mistery.intersected.vcf --json -o vcf/intersections/S19.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S20.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S20.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S20.mistery.intersected.vcf --json -o vcf/intersections/S20.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S21.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S21.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S21.mistery.intersected.vcf --json -o vcf/intersections/S21.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S22.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S22.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S22.mistery.intersected.vcf --json -o vcf/intersections/S22.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S23.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S23.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S23.mistery.intersected.vcf --json -o vcf/intersections/S23.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S24.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S24.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S24.mistery.intersected.vcf --json -o vcf/intersections/S24.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S25.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S25.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S25.mistery.intersected.vcf --json -o vcf/intersections/S25.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S26.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S26.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S26.mistery.intersected.vcf --json -o vcf/intersections/S26.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S27.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S27.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S27.mistery.intersected.vcf --json -o vcf/intersections/S27.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S28.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S28.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S28.mistery.intersected.vcf --json -o vcf/intersections/S28.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S29.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S29.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S29.mistery.intersected.vcf --json -o vcf/intersections/S29.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S30.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S30.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S30.mistery.intersected.vcf --json -o vcf/intersections/S30.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S31.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S31.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S31.mistery.intersected.vcf --json -o vcf/intersections/S31.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S32.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S32.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S32.mistery.intersected.vcf --json -o vcf/intersections/S32.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S33.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S33.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S33.mistery.intersected.vcf --json -o vcf/intersections/S33.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S34.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S34.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S34.mistery.intersected.vcf --json -o vcf/intersections/S34.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S35.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S35.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S35.mistery.intersected.vcf --json -o vcf/intersections/S35.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S36.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S36.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S36.mistery.intersected.vcf --json -o vcf/intersections/S36.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S37.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S37.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S37.mistery.intersected.vcf --json -o vcf/intersections/S37.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S38.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S38.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S38.mistery.intersected.vcf --json -o vcf/intersections/S38.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S39.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S39.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S39.mistery.intersected.vcf --json -o vcf/intersections/S39.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S40.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S40.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S40.mistery.intersected.vcf --json -o vcf/intersections/S40.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S41.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S41.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S41.mistery.intersected.vcf --json -o vcf/intersections/S41.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S42.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S42.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S42.mistery.intersected.vcf --json -o vcf/intersections/S42.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S43.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S43.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S43.mistery.intersected.vcf --json -o vcf/intersections/S43.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S44.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S44.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S44.mistery.intersected.vcf --json -o vcf/intersections/S44.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S45.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S45.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S45.mistery.intersected.vcf --json -o vcf/intersections/S45.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S46.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S46.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S46.mistery.intersected.vcf --json -o vcf/intersections/S46.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S47.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S47.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S47.mistery.intersected.vcf --json -o vcf/intersections/S47.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S48.bwa_ir_fb.norepeats.intersected.vcf --json -o vcf/intersections/S48.bwa_ir_fb.norepeats.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/intersections/S48.mistery.intersected.vcf --json -o vcf/intersections/S48.mistery.intersected.vep.json --everything --fork 28 --offline --assembly GRCh37
