DEDUP="java -jar /export/home/rgarcia/software/picard-tools-1.119/MarkDuplicates.jar"
DIR=/export/home/rgarcia/canalopatias/sam_basespace

$DEDUP REMOVE_DUPLICATES=true I=$DIR/S01.bam O=$DIR/S01_dedup.bam M=$DIR/S01.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S02.bam O=$DIR/S02_dedup.bam M=$DIR/S02.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S03.bam O=$DIR/S03_dedup.bam M=$DIR/S03.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S04.bam O=$DIR/S04_dedup.bam M=$DIR/S04.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S05.bam O=$DIR/S05_dedup.bam M=$DIR/S05.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S06.bam O=$DIR/S06_dedup.bam M=$DIR/S06.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S07.bam O=$DIR/S07_dedup.bam M=$DIR/S07.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S08.bam O=$DIR/S08_dedup.bam M=$DIR/S08.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S09.bam O=$DIR/S09_dedup.bam M=$DIR/S09.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S10.bam O=$DIR/S10_dedup.bam M=$DIR/S10.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S11.bam O=$DIR/S11_dedup.bam M=$DIR/S11.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S12.bam O=$DIR/S12_dedup.bam M=$DIR/S12.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S13.bam O=$DIR/S13_dedup.bam M=$DIR/S13.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S14.bam O=$DIR/S14_dedup.bam M=$DIR/S14.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S15.bam O=$DIR/S15_dedup.bam M=$DIR/S15.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S16.bam O=$DIR/S16_dedup.bam M=$DIR/S16.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S17.bam O=$DIR/S17_dedup.bam M=$DIR/S17.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S18.bam O=$DIR/S18_dedup.bam M=$DIR/S18.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S19.bam O=$DIR/S19_dedup.bam M=$DIR/S19.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S20.bam O=$DIR/S20_dedup.bam M=$DIR/S20.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S21.bam O=$DIR/S21_dedup.bam M=$DIR/S21.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S22.bam O=$DIR/S22_dedup.bam M=$DIR/S22.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S23.bam O=$DIR/S23_dedup.bam M=$DIR/S23.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S24.bam O=$DIR/S24_dedup.bam M=$DIR/S24.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S25.bam O=$DIR/S25_dedup.bam M=$DIR/S25.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S26.bam O=$DIR/S26_dedup.bam M=$DIR/S26.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S27.bam O=$DIR/S27_dedup.bam M=$DIR/S27.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S28.bam O=$DIR/S28_dedup.bam M=$DIR/S28.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S29.bam O=$DIR/S29_dedup.bam M=$DIR/S29.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S30.bam O=$DIR/S30_dedup.bam M=$DIR/S30.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S31.bam O=$DIR/S31_dedup.bam M=$DIR/S31.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S32.bam O=$DIR/S32_dedup.bam M=$DIR/S32.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S33.bam O=$DIR/S33_dedup.bam M=$DIR/S33.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S34.bam O=$DIR/S34_dedup.bam M=$DIR/S34.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S35.bam O=$DIR/S35_dedup.bam M=$DIR/S35.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S36.bam O=$DIR/S36_dedup.bam M=$DIR/S36.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S37.bam O=$DIR/S37_dedup.bam M=$DIR/S37.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S38.bam O=$DIR/S38_dedup.bam M=$DIR/S38.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S39.bam O=$DIR/S39_dedup.bam M=$DIR/S39.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S40.bam O=$DIR/S40_dedup.bam M=$DIR/S40.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S41.bam O=$DIR/S41_dedup.bam M=$DIR/S41.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S42.bam O=$DIR/S42_dedup.bam M=$DIR/S42.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S43.bam O=$DIR/S43_dedup.bam M=$DIR/S43.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S44.bam O=$DIR/S44_dedup.bam M=$DIR/S44.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S45.bam O=$DIR/S45_dedup.bam M=$DIR/S45.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S46.bam O=$DIR/S46_dedup.bam M=$DIR/S46.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S47.bam O=$DIR/S47_dedup.bam M=$DIR/S47.dedup_metrics
$DEDUP REMOVE_DUPLICATES=true I=$DIR/S48.bam O=$DIR/S48_dedup.bam M=$DIR/S48.dedup_metrics
