VEP=~/software/ensembl-tools-release-79/scripts/variant_effect_predictor/variant_effect_predictor.pl

$VEP -i vcf_basespace/S01.vcf -o vcf_basespace/S01.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S02.vcf -o vcf_basespace/S02.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S03.vcf -o vcf_basespace/S03.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S04.vcf -o vcf_basespace/S04.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S05.vcf -o vcf_basespace/S05.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S06.vcf -o vcf_basespace/S06.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S07.vcf -o vcf_basespace/S07.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S08.vcf -o vcf_basespace/S08.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S09.vcf -o vcf_basespace/S09.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S10.vcf -o vcf_basespace/S10.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S11.vcf -o vcf_basespace/S11.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S12.vcf -o vcf_basespace/S12.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S13.vcf -o vcf_basespace/S13.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S14.vcf -o vcf_basespace/S14.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S15.vcf -o vcf_basespace/S15.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S16.vcf -o vcf_basespace/S16.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S17.vcf -o vcf_basespace/S17.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S18.vcf -o vcf_basespace/S18.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S19.vcf -o vcf_basespace/S19.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S20.vcf -o vcf_basespace/S20.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S21.vcf -o vcf_basespace/S21.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S22.vcf -o vcf_basespace/S22.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S23.vcf -o vcf_basespace/S23.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S24.vcf -o vcf_basespace/S24.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S25.vcf -o vcf_basespace/S25.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S26.vcf -o vcf_basespace/S26.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S27.vcf -o vcf_basespace/S27.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S28.vcf -o vcf_basespace/S28.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S29.vcf -o vcf_basespace/S29.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S30.vcf -o vcf_basespace/S30.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S31.vcf -o vcf_basespace/S31.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S32.vcf -o vcf_basespace/S32.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S33.vcf -o vcf_basespace/S33.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S34.vcf -o vcf_basespace/S34.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S35.vcf -o vcf_basespace/S35.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S36.vcf -o vcf_basespace/S36.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S37.vcf -o vcf_basespace/S37.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S38.vcf -o vcf_basespace/S38.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S39.vcf -o vcf_basespace/S39.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S40.vcf -o vcf_basespace/S40.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S41.vcf -o vcf_basespace/S41.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S42.vcf -o vcf_basespace/S42.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S43.vcf -o vcf_basespace/S43.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S44.vcf -o vcf_basespace/S44.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S45.vcf -o vcf_basespace/S45.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S46.vcf -o vcf_basespace/S46.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S47.vcf -o vcf_basespace/S47.csv --everything --fork 24 --offline --assembly GRCh37
$VEP -i vcf_basespace/S48.vcf -o vcf_basespace/S48.csv --everything --fork 24 --offline --assembly GRCh37

