VEP=/home/rgarcia/downloads/ensembl-tools-release-81/scripts/variant_effect_predictor/variant_effect_predictor.pl

$VEP -i vcf/bwa_indelrealigned_fb/S01.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S01.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S02.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S02.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S03.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S03.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S04.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S04.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S05.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S05.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S06.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S06.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S07.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S07.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S08.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S08.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S09.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S09.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S10.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S10.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S11.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S11.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S12.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S12.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S13.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S13.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S14.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S14.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S15.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S15.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S16.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S16.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S17.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S17.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S18.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S18.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S19.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S19.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S20.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S20.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S21.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S21.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S22.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S22.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S23.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S23.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S24.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S24.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S25.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S25.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S26.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S26.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S27.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S27.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S28.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S28.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S29.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S29.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S30.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S30.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S31.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S31.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S32.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S32.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S33.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S33.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S34.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S34.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S35.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S35.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S36.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S36.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S37.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S37.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S38.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S38.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S39.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S39.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S40.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S40.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S41.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S41.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S42.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S42.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S43.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S43.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S44.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S44.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S45.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S45.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S46.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S46.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S47.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S47.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S48.norepeats.vcf --json -o vcf/bwa_indelrealigned_fb/S48.vep.json --everything --fork 28 --offline --assembly GRCh37
