VEP=/home/rgarcia/downloads/ensembl-tools-release-81/scripts/variant_effect_predictor/variant_effect_predictor.pl

$VEP -i vcf/bwa_indelrealigned_fb/S01.vcf --json -o vcf/bwa_indelrealigned_fb/S01.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S02.vcf --json -o vcf/bwa_indelrealigned_fb/S02.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S03.vcf --json -o vcf/bwa_indelrealigned_fb/S03.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S04.vcf --json -o vcf/bwa_indelrealigned_fb/S04.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S05.vcf --json -o vcf/bwa_indelrealigned_fb/S05.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S06.vcf --json -o vcf/bwa_indelrealigned_fb/S06.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S07.vcf --json -o vcf/bwa_indelrealigned_fb/S07.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S08.vcf --json -o vcf/bwa_indelrealigned_fb/S08.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S09.vcf --json -o vcf/bwa_indelrealigned_fb/S09.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S10.vcf --json -o vcf/bwa_indelrealigned_fb/S10.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S11.vcf --json -o vcf/bwa_indelrealigned_fb/S11.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S12.vcf --json -o vcf/bwa_indelrealigned_fb/S12.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S13.vcf --json -o vcf/bwa_indelrealigned_fb/S13.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S14.vcf --json -o vcf/bwa_indelrealigned_fb/S14.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S15.vcf --json -o vcf/bwa_indelrealigned_fb/S15.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S16.vcf --json -o vcf/bwa_indelrealigned_fb/S16.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S17.vcf --json -o vcf/bwa_indelrealigned_fb/S17.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S18.vcf --json -o vcf/bwa_indelrealigned_fb/S18.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S19.vcf --json -o vcf/bwa_indelrealigned_fb/S19.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S20.vcf --json -o vcf/bwa_indelrealigned_fb/S20.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S21.vcf --json -o vcf/bwa_indelrealigned_fb/S21.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S22.vcf --json -o vcf/bwa_indelrealigned_fb/S22.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S23.vcf --json -o vcf/bwa_indelrealigned_fb/S23.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S24.vcf --json -o vcf/bwa_indelrealigned_fb/S24.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S25.vcf --json -o vcf/bwa_indelrealigned_fb/S25.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S26.vcf --json -o vcf/bwa_indelrealigned_fb/S26.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S27.vcf --json -o vcf/bwa_indelrealigned_fb/S27.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S28.vcf --json -o vcf/bwa_indelrealigned_fb/S28.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S29.vcf --json -o vcf/bwa_indelrealigned_fb/S29.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S30.vcf --json -o vcf/bwa_indelrealigned_fb/S30.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S31.vcf --json -o vcf/bwa_indelrealigned_fb/S31.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S32.vcf --json -o vcf/bwa_indelrealigned_fb/S32.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S33.vcf --json -o vcf/bwa_indelrealigned_fb/S33.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S34.vcf --json -o vcf/bwa_indelrealigned_fb/S34.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S35.vcf --json -o vcf/bwa_indelrealigned_fb/S35.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S36.vcf --json -o vcf/bwa_indelrealigned_fb/S36.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S37.vcf --json -o vcf/bwa_indelrealigned_fb/S37.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S38.vcf --json -o vcf/bwa_indelrealigned_fb/S38.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S39.vcf --json -o vcf/bwa_indelrealigned_fb/S39.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S40.vcf --json -o vcf/bwa_indelrealigned_fb/S40.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S41.vcf --json -o vcf/bwa_indelrealigned_fb/S41.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S42.vcf --json -o vcf/bwa_indelrealigned_fb/S42.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S43.vcf --json -o vcf/bwa_indelrealigned_fb/S43.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S44.vcf --json -o vcf/bwa_indelrealigned_fb/S44.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S45.vcf --json -o vcf/bwa_indelrealigned_fb/S45.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S46.vcf --json -o vcf/bwa_indelrealigned_fb/S46.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S47.vcf --json -o vcf/bwa_indelrealigned_fb/S47.vep.json --everything --fork 28 --offline --assembly GRCh37
$VEP -i vcf/bwa_indelrealigned_fb/S48.vcf --json -o vcf/bwa_indelrealigned_fb/S48.vep.json --everything --fork 28 --offline --assembly GRCh37
