QUALIMAP=/home/rgarcia/downloads/qualimap_v2.0/qualimap
BED=/mnt/f/rgarcia/canalopatias/targets/Miocardiopatias_y_canalopatias_Amplicons.bed

$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/25_S25_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/25_S25_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/44_S44_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/44_S44_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/19_S19_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/19_S19_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/4_S4_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/4_S4_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/41_S41_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/41_S41_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/39_S39_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/39_S39_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/23_S23_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/23_S23_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/34_S34_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/34_S34_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/22_S22_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/22_S22_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/30_S30_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/30_S30_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/20_S20_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/20_S20_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/24_S24_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/24_S24_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/3_S3_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/3_S3_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/35_S35_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/35_S35_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/14_S14_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/14_S14_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/32_S32_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/32_S32_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/27_S27_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/27_S27_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/5_S5_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/5_S5_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/37_S37_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/37_S37_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/28_S28_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/28_S28_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/1_S1_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/1_S1_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/7_S7_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/7_S7_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/45_S45_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/45_S45_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/42_S42_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/42_S42_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/9_S9_L001_dedup_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/9_S9_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/43_S43_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/43_S43_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/18_S18_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/18_S18_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/9_S9_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/9_S9_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/40_S40_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/40_S40_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/26_S26_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/26_S26_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/16_S16_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/16_S16_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/47_S47_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/47_S47_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/2_S2_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/2_S2_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/10_S10_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/10_S10_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/12_S12_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/12_S12_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/46_S46_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/46_S46_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/33_S33_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/33_S33_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/29_S29_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/29_S29_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/15_S15_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/15_S15_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/21_S21_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/21_S21_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/Undetermined_S0_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/Undetermined_S0_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/17_S17_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/17_S17_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/38_S38_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/38_S38_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/6_S6_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/6_S6_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/13_S13_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/13_S13_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/8_S8_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/8_S8_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/11_S11_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/11_S11_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/36_S36_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/36_S36_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/31_S31_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/31_S31_L001.pdf
$QUALIMAP bamqc --feature-file $BED -c -outformat PDF -bam /mnt/f/rgarcia/canalopatias/sam/48_S48_L001_dedup.bam -outfile  /mnt/f/rgarcia/canalopatias/qc/48_S48_L001.pdf
