python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/38_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/38_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/39_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/39_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/20_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/20_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/48_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/48_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/24_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/24_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/34_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/34_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/22_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/22_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/47_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/47_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/33_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/33_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/30_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/30_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/43_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/43_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/14_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/14_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/35_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/35_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/26_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/26_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/12_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/12_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/23_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/23_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/45_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/45_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/16_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/16_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/18_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/18_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/28_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/28_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/21_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/21_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/13_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/13_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/40_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/40_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/25_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/25_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/17_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/17_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/31_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/31_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/11_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/11_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/36_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/36_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/15_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/15_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/27_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/27_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/19_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/19_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/37_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/37_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/46_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/46_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/42_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/42_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/29_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/29_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/41_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/41_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/32_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/32_S1_missing.pickle
python missing_vkeys_from_vcf.py --vcf ../vcf/hlplxI_BS_AOB/44_S1.vcf --collection scd --outpickle ../vcf/hlplxI_BS_AOB/44_S1_missing.pickle
